### ISSUE TITLE
Is this real?

### ISSUE THREAD

**Issue by CrazyPython** [bullgit/nsabots.txt#1]
Probably not. They probably ignore it entirely.

**Comment by Haroenv** [comment]
It's very real and it works perfectly 🆗

**Comment by CrazyPython** [comment]
Wait... this is bullgit. Also, any proof? How did you find out?

**Comment by LukyVj** [comment]
Welcome to the real world. @CrazyPython .

**Comment by Haroenv** [comment]
THIS ISSUE HAS BEEN CLOSED ON REQUEST OF THE NATIONAL SECURITY AGENCY OF THE UNITED STATES OF AMERICA

**Comment by dervondenbergen** [comment]
😨
